### ISSUE TITLE
Spawning and bundles

### ISSUE THREAD

**Issue by ksf** [Zeenobit/moonshine_kind#1]
This is a purely ergonomic issue, but unlike `spawn` `spawn_instance` does not work on `Bundle`s, requiring manual `inserts`, which then returns `Commands` instead of `InstanceCommands`, turning code like

```rust
let actor_a: Entity = commands.spawn(ActorBundle::named("Alice")).id();

commands.spawn(Place::new([actor_a]));
```

into

```rust
let mut actor_a = commands.spawn_instance(Actor::default());
actor_a.insert(Name::new("Alice"));
let actor_a: Instance<Actor> = actor_a.instance();

commands.spawn(Place::new([actor_a]));
```

Changing `fn spawn_instance<T: Kind + Component>` to `fn spawn_instance<T: Kind + Bundle>` goes a long way, leaving some awkwardness around `Instance<ActorBundle>` not fitting into an `Instance<Actor>` slot and casts not being static:

```rust
impl Kind for ActorBundle {
    type Filter = (With<Actor>, With<Name>);
    fn is_convertible_to<U: Kind>() -> bool {
        TypeId::of::<U>() == TypeId::of::<Self>()
            || TypeId::of::<U>() == TypeId::of::<Any>()
            || TypeId::of::<U>() == TypeId::of::<Actor>()
            || TypeId::of::<U>() == TypeId::of::<Name>()
    }
}


let actor_a = commands
    .spawn_instance(ActorBundle::named("Alice"))
    .instance()
    .cast_into::<Actor>()
    .unwrap();
```

Which of course can also be worked around by using `Instance<ActorBundle>` instead of `Instance<Actor>` in `Place` which is quite sensible in this and many (if not the majority of) cases but for generality's sake it would be nice to have automatic casts from `Bundle`s to all their component `Components` (and maybe use `into()`). My type level black belt is in Haskell, not Rust, so I'm officially out of ideas.

The `InstanceCommands` vs. `Commands` thing is probably best solved by upstreaming into bevy.

**Comment by Zeenobit** [comment]
I've ran into the issue you're presenting in my personal project too. But I'm hesitant in allowing `spawn_instance` to accept `Kind + Bundle` to allow this pattern of usage. Mainly because it gives the user a footgun to break "kind-safety".
For example:
```rust
#[derive(Bundle)]
struct ActorBundle {
  //actor: Actor, /* <--- !!! */
  name: Name,
}
...

let actor: Instance<Actor> = commands
    .spawn_instance(ActorBundle::named("Alice"))
    .instance()
    .cast_into::<Actor>()
    .unwrap();
```
This code would compile ok and even be ok at call site (since cast doesn't actually do a query check). So I'm concerned that such usage would lead to subtle bugs way later than the source of it.

This would be less of a concern if this crate was upstreamed into Bevy proper. Because then the implementation of `is_convertible_to` would be derived by macro, and so removal of a component would make the cast fail.

I'm keeping the issue open because I think it's a legitimate issue. But I don't think allowing `Kind + Bundle` is the best option.

**Comment by ksf** [comment]
You're certainly right about that footgun. Personally I don't like `unsafe` in places where they multiply, with something like

```rust
pub unsafe trait Subkind<Super: Kind>: Kind {}

impl<T: Kind> Instance<T> {
    pub fn cast<Other>(&self) -> Instance<Other>
    where
        Other: Subkind<T>,
    {
        unsafe { Instance::<Other>::from_entity_unchecked(self.entity()) }
    }
}
```

they could be placed right next to the struct definition

```rust
unsafe impl Subkind<ActorBundle> for Actor
```

, you'd only need one `unsafe` for an arbitrary number of casts, and they can also be derived via macro with only the definition of `ActorBundle`. (modulo `Bundle`s not being `Kind` because `Kind` and thus `Instance` kinda implies `WorldQuery` which `Bundle`s aren't).

**Comment by Zeenobit** [comment]
This issue should be resolved with [`KindBundle`](https://docs.rs/moonshine-kind/latest/moonshine_kind/trait.KindBundle.html)
